rx-angular/rx-angular

libs/template/src/lib/template.module.ts
There's no need to add Angular modules to `imports` when we don't have `declarations`.
After this refactor, I don't see the need for the `MODULES` constant.
=> refactor(template): remove unnecessary metadata from template module

libs/state/package.json, libs/template/package.json
This is technically a breaking change, but it's default for Angular package libraries, so it shouldn't be a big deal.
Note that we currently use `tslib` v1.11.x in this workspace, but Angular CLI 9.0.x apps come with v1.10.x out-of-the-box.
=> feat: add back tslib dependency

package.json
It's doesn't seem to be needed anymore. This has changed a lot in the Angular 9.x releases.
If it's needed again, it should be something like
```
"postinstall": "ngcc && ngcc --properties main"
```
The last part is for producing UMD bundles for Jest.
=> chore: remove ngcc postinstall hook

libs/template/src/lib/let/let.directive.ts
otherwise it is not possible to set the strategy via: `<div *rxLet="o$; strategy: 'strat'; let o"></div>`
=> fix(let) fix strategy input binding

libs/template/src/lib/core/render-aware/render-aware_creator.ts
if strategy is provided as observable, mergeAll() operator just causes the string e.g. "local" to get emitted as "l", "o", "c", "a", "l".
=> fix(render-aware) fixed broken strategy selection

libs/template/src/lib/core/render-aware/promise-duration-selector.ts
…which caused crashes when zone was not included.
There were missing brackets.
=> fix(template) fixed a bug in the promise-duration-selector 

libs/state/spec/core/operators/distinctUntilSomeChanged.spec.ts, libs/state/src/lib/core/operators/distinctUntilSomeChanged.ts
thx to @Karnaukhov-kh who pointed out some problems regarding the `distinctUntilSomeChanged` operator
- fixed typing which led to messy workarounds when using KeyCompareMap
- updated jsdocs accordingly
- increased test coverage to 100%
=> fixed distinctUntilSomeChanged issues after review

libs/template/spec/core/utils/zone-check.spec.ts, libs/template/spec/fixtures/fixtures.ts, libs/template/src/lib/core/utils/zone-checks.ts
This pull request aims to match the changes introduced here: ngrx/platform#2547.
It changes the way zone.js gets detected.
=> fix: detect zone.js by using runOutsideAngular()

libs/template/src/lib/core/utils/zone-checks.ts
The changes introduced by this pull request will make sure that each instance is only tested once to limit the function calls that are made to test if something is an NgZone or a NoopNgZone.
=> feat(template): Cache zone.js detection per instance

libs/state/perf/index.ts, libs/state/perf/utils/index.ts
This pull request just adds three "e"s to fix a typo in function name.
=> fix typo in function name

libs/template/src/lib/core/render-aware/render-aware_creator.ts
Loosing state on resubscribe fixed. Removed switchMap as we now use connect to set the strategy.
=> fix(template): render aware strategy handling stable on resubscribe

apps/experiments/src/app/state/rx-state.menu.ts, apps/experiments/src/app/state/rx-state.module.ts, apps/experiments/src/app/state/rx-state.routes.ts, apps/experiments/src/app/state/selectslice/select-slice.component.html, apps/experiments/src/app/state/selectslice/select-slice.component.ts, libs/state/spec/rxjs/operators/selectSlice.spec.ts, libs/state/src/lib/rxjs/operators/selectSlice.ts
- removed `| null` from selectSlice's typing. this breaks apps which run in strictMode.
- added usage to `selectSlice.spec.ts` to verify typing in strictMode
- added usage in `experiments` app to verify typing in non-strictMode
closes #177
=> fix(state): fixed selectSlice typing

libs/template/src/lib/core/render-aware/render-aware_creator.ts, libs/template/src/lib/core/utils/template-manager.ts, libs/template/src/lib/let/let.directive.ts
This PR adds `ng-template` bindings to be used with `LetDirective`. With this, we can create and bind templates for different state of an observable:
- **next** - when values are emitted
- **complete** - on observable completion 
- **error** - on observable error
- 🔥 **suspense** 🔥 - render something before the first value is emitted from an observable
Work is still in progress. The initial implementation is there but there's still some things to do before we could say it's 100% completed:
Here is some small, example component that uses the newest syntax:
```ts
@Component({
selector: 'let-template-binding',
template: `
<button [unpatch] (click)="signals$?.complete()">
complete
</button>
<button [unpatch] (click)="signals$?.next(random())">
next
</button>
<button [unpatch] …
```
=> Template bindings for rxLet

libs/template/src/lib/core/utils/get-global-this.ts
Should close #66  
Simply changed return order in getGlobalThis to ```((window as any) || (self as any) || (globalThis as any))```. 
Tested in stateDemo/demo-basics.
What was checked:
- Push pipe
- RxLet
- Unpatch
Tested environments:
- ✔️ Chrome 69 (not supporting globalThis)
- ✔️ Edge 44 (not supporting globalThis)
- ✔️ Our jest tests
What wasn't checked:
- 🤞  SSR. In theory, it should work because both window and self will be undefined. And there probably will be [domino](https://www.npmjs.com/package/domino) or something similar.
- ❌ IE 11. State demo not launching there. But the only problem in IE was the lack of support for globalThis. Overall template package works in IE with polyfill for globalThis.
Hope I'm not missing anything.
=> Fix for globalThis issue in old browsers.

libs/state/spec/core/accumulation-observable.spec.ts, libs/state/src/lib/core/accumulation-observable.ts
When an error happens inside the connect method it is not appearing in the console. Only can be reproduced if we use select() to get data from the source. If we use $ everything is fine.
Sometime after 1.0 we introduced publish() + publishReplay(1) in state accumulator.
```
const signal$ = merge(
stateObservables.pipe(
distinctUntilChanged(),
mergeAll(),
observeOn(queueScheduler)
),
stateSlices.pipe(observeOn(queueScheduler))
).pipe(
scan(stateAccumulator, {} as T),
tap(newState => (compositionObservable.state = newState)),
publish()
);
const state$ = signal$.pipe(publishReplay(1));
```
And after that errors disappeared. If we keep `state$ = signal$` without publishReplay errors appear as they should do.
Not the perfect solution but gets the job done. We can adjust tap a tiny bit.
``` …
```
=> Log errors in accumulator

package.json, tsconfig.base.json
Downgraded to `ng-packagr 9.1.5`.
See changelog: https://github.com/ng-packagr/ng-packagr/blob/master/CHANGELOG.md#1000-next0-2020-05-06
=> Fix es5 builds

.gitignore, angular.json, libs/state/jest.config.js, libs/template/jest.config.js
This PR implements testbade generation and moves the output in the docs folder.
This has a couple of implications
- This means we would self host our test coverage bades
- We can have badges per repo
- we can hose Istambul output as-is
- we lose/drop corealls
- we have to integrate test-docs generation in the release step 
Let me know your thoughts on that.
=> docs(test-coverage): added test coverage to docs folder

angular.json, libs/template/spec/core/render-aware/render-aware_creator.spec.ts, libs/template/spec/core/utils/create_properties-weakmap.spec.ts, libs/template/spec/core/utils/get-global-this.spec.ts, libs/template/spec/core/utils/view-engine-checks.spec.ts, libs/template/spec/core/utils/zone-check.spec.ts, libs/template/spec/let/let.directive.complete.spec.ts, libs/template/spec/let/let.directive.error.spec.ts, libs/template/spec/let/let.directive.next.spec.ts, libs/template/spec/let/let.directive.strategy.spec.ts, libs/template/spec/let/let.directive.template-binding.all.spec.ts, libs/template/spec/let/let.directive.template-binding.no-complete.spec.ts, libs/template/spec/let/let.directive.template-binding.no-error.spec.ts, libs/template/spec/let/let.directive.template-binding.no-suspense.spec.ts, libs/template/spec/push/push.pipe.service.spec.ts, libs/template/spec/push/push.pipe.spec.ts, libs/template/spec/render-strategies/experiments/task-time.spec.ts, libs/template/spec/render-strategies/rxjs/coalesceWith.spec.ts, libs/template/spec/render-strategies/static/static-coalesce.spec.ts, libs/template/spec/render-strategies/static/static-schedule-and-coalesced.spec.ts, libs/template/spec/render-strategies/static/static-schedule.spec.ts, libs/template/spec/render-strategies/strategy.spec.ts, libs/test-helpers/src/lib/utils/index.ts, libs/test-helpers/src/lib/utils/mock-console.ts
Now if you run template tests console output will be overwhelmed with `console.error` output. Solution for this is to mock console implementation with `jest.spyOn(console, 'error').mockImplementation()`.
- Test commands were not working (neither in this branch or master). To fix that I've extended `angular.json` a little bit. Paths to `tsconfig.spec.json` were added to state -> test -> options and template -> test -> options.
- `mockConsole` method added to `test-helpers/src/lib/utils/mock-console.ts`
- All template tests now importing this helper and running it in jest `beforeAll` inside main `describe` blocks.
run `yarn run nx test template` & `yarn run nx test state`.
=> Mock console in tests

libs/state/src/lib/rxjs/operators/selectSlice.ts
The goal of this PR is to fix https://github.com/BioPhoton/rx-angular/issues/177. As provided by the author within his playground demo, `selectSlice` incorrectly infers the type of a slice when the type provided to `RxState` declaration is not a concrete type but a generic subtype of one.
To verify if the `selectSlice` does what it is supposed to, I created a small example that can be played with even inside our own RxAngular repo.
```typescript
interface MyState {
title: string;
items: string[];
panelOpen: boolean;
}
const state$: Observable<MyState> = of({
items: [''],
panelOpen: true,
title: 'dwadaw'
});
// typical use-case, `data` should be of the correct type
const slice$ = state$.pipe(
selectSlice(['items'])
).subscribe(data => data.items);
// example from christianacca reproduced, …
```
=> Fixed inferring type from a subtype of a state provided for RxState

apps/template-demo/src/app/examples/template-binding/let-template-binding/examples/let-template-binding-subject-example.component.ts, libs/template/src/lib/core/render-aware/render-aware_creator.ts, libs/template/src/lib/let/let.directive.ts, libs/template/src/lib/render-strategies/strategies/local.strategy.ts
This PR solves adds several things and solves small issues:
- adds `error` and `complete` observable notification handling for `LetDirective` via a custom operator
- embeds `rxSuspense` template to the view on reset of the bound observable
- invokes `detechChanges()` for `LocalStrategy` differently (with no worries that `ChangeDetectionRef` instance will drop component's reference)
- adds "reset" button to the `template-demo` page with template binding example
=> Handling of error and complete notifications for LetDirective (and more)

libs/state/src/lib/core/utils/safe-pluck.ts
During review session of safePluck I misguided Julian and we used `isObject` from node instead of `isObjectGuard` from our typings. That's why state builds are failing at the moment.
- `safe-pluck.ts`. `isObjectGuard` used instead of `isObject`.
This is only a change in the internals of `safePluck` and should not affect its output.
=> Use correct object guard in safePluck

apps/state-demo/src/app/examples/demo-basics/Readme.md, libs/state/README.md, libs/state/docs/api/rx-state.md, libs/state/docs/snippets/selecting-the-viewmodel.md, libs/template/README.md
Fixes in GitHub `.md` files for upcoming web docs.
- Relative links for images replaced with https://raw.githubusercontent.com/.
- ⚠️ Coverage badges links also changed to raw file links.
- Relative links in the state docs replaced with global links.
- $ heading in `rx-state.md` changed to $ (state observable). Otherwise, it's not working as anchor link :)
=> State docs fixes

libs/template/spec/core/utils/template-manager_creator.spec.ts, libs/template/src/lib/core/utils/coalescing-manager.ts, libs/template/src/lib/core/utils/template-manager_creator.ts, libs/template/src/lib/let/let.directive.ts
This PR touches on a few things that came up during https://github.com/BioPhoton/rx-angular/pull/222. Each of those things (and some additional ones) will be explained in a separate paragraph with proposals on how to resolve those.
There was a TODO comment for me to add a comment on an implementation detail explaining why there is a condition on displaying "suspense" or "next" in the `LetDirective`. I added those and also refactored this part of a code for further clarity.
Latest commits broke template-binding example in `template-demo` app. Considering this as a primary example with one of the most basic and simplest use-cases for the `LetDirective`, this got my attention. Solution was rather simple: inside `TemplateManager`'s implementation there were two lines of code:
```ts …
```
=> Updating testing scenarios and adding tests for TemplateManager (and more)

libs/template/spec/let/let.directive.next.spec.ts, libs/template/spec/let/let.directive.template-binding.no-suspense.spec.ts, libs/template/src/lib/let/let.directive.ts
The let directive currently calls `this.templateManager.displayView('rxNext');` in the `ngOnInit` method when no `rxSuspense` template was found. This is not only an issue as this is against the idea of "lazy rendering". 
If your value you bound to the `LetDirective` does not emit any value until the `LetDirective` renders it's initial view, you will end up in runtime errors since all your ViewBindings are now bound to an undefined object.
Also, in my opinion the `LetDirective` should really not render _ANYTHING_ until the first "defined" ( !== undefined ) value appears.  Of course only if you haven't provided a `rxSuspense` template.
* revert changes in `let.directive.ts`
* `yarn nx s tour-of-heroes`
* navigate to a detail-view from the dashboard
* you will get an `core.js:4196 ERROR …
=> fix(template): fix let directive initial view

libs/template/README.md, libs/template/docs/push.md
This PR fixes a few wrong links to the `LetDirective` doc.
=> Fixed references to docs for LetDirective

.github/workflows/docs.yml
currently docs are not generated correctly via github actions. With `force: true` it should work correctly
=> chore: force push on docs generation action

libs/state/docs/api/transformation-helpers/array/update.md
Just a very minor fix in the docs – the name of the property should be `creatureToUpdate` instead of `creatureToRemove`.
=> docs(state): fix wrong property name

libs/template/spec/core/render-aware/render-aware_creator.spec.ts, libs/template/src/lib/core/model.ts, libs/template/src/lib/core/render-aware/render-aware_creator.ts, libs/template/src/lib/let/let.directive.ts, libs/template/src/lib/push/push.pipe.ts
This PR normalized the 4 states for all templates.
It introduces:
the 4 states suspense, next, error and complete
RxTemplateObserver holds the Observer callbacks plus the suspense callback
RxViewContext which holds the default properties for a ViewContext
=> Harmonize reactive context

libs/template/src/lib/render-strategies/strategies/global.strategy.ts, libs/template/src/lib/render-strategies/strategies/local.strategy.ts, libs/template/src/lib/render-strategies/strategies/native.strategy.ts, libs/template/src/lib/render-strategies/strategies/noop.strategy.ts, libs/template/src/lib/render-strategies/strategies/strategies-map.ts
This PR aims to clearly document the following strategies and their tables:
- noop
- native
- global
- local
The tables now have the following columns:
| Name      | Zone Agnostic | Render Method     | Coalescing         | Scheduling                 |
| --------- | --------------| ----------------- | ------------------ | -------------------------- |
| `local`   | ✔             | 🠗 `detectChanges` | ✔ ComponentContext | `requestAnimationFrame`   |
| `global`  | ✔             | ⮁ `ɵmarkDirty`    | ✔ RootContext     | `requestAnimationFrame`   |
| `detach`  | ✔             | ⭭ `detectChanges` | ✔ ComponentContext | `requestAnimationFrame`   |
| `noop`    | ✔             | - `noop`          | ❌                 | ❌                        |
| `native`  | ❌             | ⮁ `markForCheck` | ✔ …
=> fix(strategies): complete API docs

libs/template/spec/core/utils/zone-check.spec.ts
implemented missing tests for zone-checks.ts in regard of #202
=> test(zone-check): implemented missing zone-check tests

libs/state/spec/rxjs/operators/selectSlice.spec.ts, libs/state/src/lib/rxjs/operators/selectSlice.ts
As reported in this issue: #281 the `selectSlice` operator emits slices where values potentially can be undefined. From my personal experience I can tell that this behavior often leads to the usage of `filter` to check if all selected keys are really defined.
I have implemented a simple check if the length of the `definedKeys` is less than the length of the provided `keys` array.
```ts
const definedKeys = keys
// filter out undefined properties e. g. {}, { str: undefined }
.filter((k) => state.hasOwnProperty(k) && state[k] !== undefined);
if (definedKeys.length < keys.length) {
return undefined;
}
```
* implemented new undefined check
* added tests for the new behavior
=> fix(selectSlice): fixed undefined selected key behavior

libs/template/spec/render-strategies/render-strategies/global.strategy.spec.ts
As we are clearly not able to test the internals of the `ɵmarkDirty` function, and that is checking if a proper flag was set on the `__ngContext__` of the component  - we could change the approach.
I trust the Angular team to properly test the internals of the `ɵmarkDirty` function - they created it. Rather than ensuring for the second time that the `ɵmarkDirty` is working as expected, we should focus on our side of the code.
That's why my proposal is rather simple - to check if the call on the `ɵmarkDirty` was made on the component, rather than check the internal functionality of `ɵmarkDirty`.
---
If you think that this solution is not satisfactory, you can go ahead and reject it. It's only a proposal :)
=> Proposal for updating tests for ɵmarkDirty

libs/template/docs/api/let-directive.md, libs/template/src/lib/experimental/unpatch/events/unpatch-events.directive.ts, libs/template/src/lib/let/let.directive.ts
As per https://github.com/rx-angular/rx-angular/issues/313:
- Updated jsdoc example for `LetDirective`.
- Added description for the input binding for the `UnpatchEventsDirective` for it to be a little bit more clearer that it doesn't have to be provided.
=> Updated docs for LetDirective and UnpatchEventDirective

libs/state/docs/snippets/manage-global-state.md
Type of PR:
- Reporting a bug
- Discussing the current state of the code
- Submitting a fix ✔
- Proposing new features
- Becoming a maintainer
Summary:
With the current document of [Managing Global State](https://github.com/rx-angular/rx-angular/blob/master/libs/state/docs/snippets/manage-global-state.md) new developers will following the snippet code to implement it in their code. the code that they implement will not work. because in the snippet code in the AppComponent they way of calling the `connect()` method is wrong: `this.connect("tasks", this.tasksService.fetchTasks())`. 
the correct way is to call the `connect()` method of `state` property: `this.state.connect("tasks", this.tasksService.fetchTasks())`
=> Improve Document: Manage Global State

apps/demos/src/app/features/template/rx-let/let-template-binding/examples/let-template-binding-subject-example.component.ts, apps/demos/src/app/features/template/rx-let/let-template-binding/let-template-binding.module.ts, apps/demos/src/app/features/template/rx-let/let-template-binding/let-template-binding.routes.ts
"Template Bindings" demo in the "demos" app was forwarding to the error page. This PR serves as a fix for that, enabling this demo.
=> Enabled Template Bindings demo in the "demos" app

apps/demos/src/app/features/template/push/push-basic-example/push-basic-example.component.ts, apps/demos/src/app/features/template/push/push-basic-example/push-basic-example.module.ts, libs/template/src/lib/core/render-aware/render-aware_creator.ts
fixed custom `renderWithLatestStrategy` operator. It completed instantly which sometimes leads to over-emitting push pipes. The `coalesceWith` operator emits instantly when the subscription completes.
=> RenderAware fix

libs/template/spec/let/let.directive.complete.spec.ts, libs/template/spec/let/let.directive.error.spec.ts, libs/template/spec/let/let.directive.template-binding.all.spec.ts, libs/template/spec/let/let.directive.template-binding.no-complete.spec.ts, libs/template/spec/let/let.directive.template-binding.no-error.spec.ts, libs/template/spec/let/let.directive.template-binding.no-suspense.spec.ts, libs/template/spec/push/push.pipe.service.spec.ts, libs/template/spec/render-strategies/render-strategies/global.strategy.spec.ts
`async` is deprecated and replaced with `waitForAsync` since Angular v10.1.0
=> refactor: replace deprecated async with waitForAsync

libs/state/spec/core/utils/safe-pluck.spec.ts, libs/state/spec/rx-state.service.spec.ts, libs/state/src/lib/rx-state.service.ts
Currently, the `RxState#get` method returns `{}` as initial value. Furthermore it returns `{}` if the state is empty and you want to read a property, but it should be `undefined` instead.
```ts
const state = new RxState();
state.get('prop'); // will return {}
const state2 = new RxState();
state2.set({ prop2: 'someVal' });
state2.get('prop'); // will return undefined
```
I have fixed this behavior by always returning `undefined` if the state is empty. In all other cases `safePluck` will do the work for us. I have added some tests to ensure this behavior.
=> Fix state get return value

docs/index.html
Changed docs router from hash-based to history-based
⚠️ After the merge, existing links to our web docs might be broken
=> docs(web): enable history based router

docs/index.html, docs/web/partials/_sidebar.md
History based route not working properly with Github Pages. Direct links open 404 page. 🤕
The workaround for this is to serve the whole documentation using redirects from the 404 page. This hack is not recommended and not SEO friendly.
See these issues: 
- https://github.com/docsifyjs/docsify/issues/238
- https://github.com/facebook/create-react-app/issues/1765
=> docs(fix) switch back to has route

apps/demos/src/app/features/experiments/structural-directives/rx-let-poc/rx-let-poc.component.ts, apps/demos/src/app/features/experiments/structural-directives/rx-let-poc/rx-let-poc.module.ts, apps/demos/src/app/features/experiments/structural-directives/rx-let-poc/rx-let-suspense-trigger.directive.ts, apps/demos/src/app/shared/rx-angular-pocs/render-stragegies/default-strategies.ts, apps/demos/src/app/shared/rx-angular-pocs/render-stragegies/model.ts, apps/demos/src/app/shared/rx-angular-pocs/render-stragegies/strategy-helper.ts
This PR tries to evaluate the pros/cons edgecases of detaching the EmbeddedView after error or complete.
=> feat(template):detach on complete and error

libs/template/src/lib/experimental/viewport-prio/viewport-prio.experimental.directive.ts
Hey! I didn't open an issue since this seems to be a tiny change. Currently, the `IntersectionObserver` is not disconnected and prevents the `ViewportPrioDirective` and `LetDirective` to be garbage collected.
=> fix(viewport-prio): disconnect the observer to allow the directive to be GCed

angular.json, libs/state/tsconfig.lib.json, libs/state/tsconfig.lib.prod.json, libs/template/tsconfig.lib.json, libs/template/tsconfig.lib.prod.json
Note that `package` builder doesn't support configurations. You can check it with:
```js
$ node
{ execSync } = require('child_process')
packageImpl = require('@nrwl/angular/src/builders/package/package.impl')
run = packageImpl.run
packageImpl.run = (options, context) => {
console.log(options.tsConfig);
return run(options, context);
}
execSync('yarn build template --prod --skip-nx-cache').toString()
```
=> build: do not publish Ivy compiled packages

libs/template/spec/let/let.directive.complete.spec.ts, libs/template/spec/let/let.directive.error.spec.ts, libs/template/spec/let/let.directive.next.spec.ts, libs/template/spec/let/let.directive.rendered.spec.ts, libs/template/spec/let/let.directive.strategy.spec.ts, libs/template/spec/push/push.pipe.service.spec.ts, libs/template/spec/push/push.pipe.spec.ts, libs/template/src/index.ts, libs/template/src/lib/experimental/unpatch/events/index.ts, libs/template/src/lib/experimental/unpatch/index.ts, libs/template/src/lib/experimental/viewport-prio/index.ts, libs/template/src/lib/experimental/viewport-prio/viewport-prio.experimental.directive.ts, libs/template/src/lib/let/index.ts, libs/template/src/lib/push/index.ts
=> build: remove barrel files for modules and directives since it breaks metadata collection

libs/template/src/lib/core/utils/get-global-this.ts
Previously it was throwing `window is not defined` in Node.js environment.
=> fix: use Angular variable to get the `globalThis`

libs/template/src/lib/core/model.ts
> Warning: Entry point '@rx-angular/template' contains deep imports into 'node_modules/rxjs/internal/types'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
=> chore(build): remove deep import

libs/template/tsconfig.schematics.json
Currently due to the root path src folder is not generated in the dist folder.
and the schematics look for below files when executed inside src 
"schema": "./src/commands/ng-add/schema.json",
"factory": "./src/commands/ng-add/index#ngAdd",
The solution was one of the below.
1. Change the root path from tsconfig.schematics.json
2. move files outside src and refer the path, and change the root path as well.
=> fix: ng-add for rx-template

apps/demos/src/app/app.module.ts, apps/demos/src/app/features/template/rx-let/basic/rx-let-basic.component.ts, apps/demos/src/app/features/template/rx-let/basic/rx-let-basic.module.ts, apps/demos/src/app/features/template/rx-let/let-template-binding/examples/let-template-binding-http-example.component.ts, apps/demos/src/app/features/template/rx-let/let-template-binding/examples/let-template-binding-subject-example.component.ts, apps/demos/src/app/shared/debug-helper/strategy-select/strategy-select.module.ts, libs/cdk/src/lib/model.ts, libs/cdk/src/lib/template-management/template-manager.ts, libs/cdk/src/lib/utils/notification-transforms.ts, libs/cdk/src/lib/utils/rxMaterialize.ts, libs/cdk/src/lib/utils/templateNotifier.ts, libs/template/spec/let/let.directive.template-binding.no-complete.spec.ts
When an observable bound to an `rxLet` (TemplateManager) `completes` or `errors` it is not possible to display the latest value in the provided templates.
I have improved the `RxTemplateManager` and `templateNotifier` so that the `RxViewContext` will always contain the latest emitted value of the bound value.
A little example:
Example code:
```html
<ng-template #error let-value let-error="$error">
<div>
<mat-icon class="error-icon">thumb_down</mat-icon>
<h2>{{ error }}</h2>
<strong>Last valid value: {{ value }}</strong>
</div>
</ng-template>
```
```html
<ng-template #complete let-value>
<div>
<mat-icon class="notification-icon complete-icon">thumb_up</mat-icon>
<h2>Completed!</h2>
<strong>Last valid value: {{ value }}</strong>
</div>
</ng-template>
```
Additionally we should talk about …
=> feat(cdk): improve template manager view-context

angular.json, nx.json
set `@rx-angular/template` as `implicitDependency` for `@rx-angular/cdk`. This ensures `cdk` gets build whenever `template` gets build. This way we ensure `template` has a built version of `cdk` whenever it needs
=> fix(build): make sure cdk gets build when template gets build

.github/workflows/label.yml
Referring to [this comment](https://github.com/actions/labeler/issues/12#issuecomment-670967607) should fix the labeler not working from forks.
=> Fix labeler from forks

libs/cdk/src/lib/template-management/list-template-manager.ts
The current implementation returns `[]` when no changes were detected from the `IterableDiffer`. This causes the `switchMap` to stop emitting values which in turn results in no `renderCallback` called.
```ts
// list-template-manager.ts 119
switchMap(([{ changes, items }, strategy]) => {
if (!changes) {
return [];
}
```
When u put an empty array `[]` into the `rxFor` directive (aka listManager), the `renderCallback` won't emit properly. Imho a new value which results in no change should trigger `renderCallback` since the change got processed.
```ts
// list-template-manager.ts 119
switchMap(([{ changes, items }, strategy]) => {
if (!changes) {
return of([]); // of should be fine even though it completes since this gets ignored currently? Do we have to keep future rxComplete, rxError …
```
=> fix(list-manager): fix list manager return value

apps/demos/src/app/rx-angular-pocs/cdk/utils/zone-agnostic/rxjs/operators/fromEvent.ts, libs/cdk/src/lib/zone-less/rxjs/operators/fromEvent.ts
Bug: 
fromEvent always added listened on `window` element
[Stackblitz reproduction](https://stackblitz.com/edit/rx-angular-unpathced-bug)
=> fix fromEvent always subscribing on document

libs/cdk/src/lib/zone-configuration/model/configurations.types.ts
Added Typescript docs comment to zone configuration methods.
This way we have nice IDE inline docs of all that details ;)
=> feat(zone-configuration): add ts docs to zone configuration

apps/demos/src/app/rx-angular-pocs/template/directives/unpatch/unpatch-events.directive.ts, libs/cdk/zone-less/src/browser/browser.ts, libs/cdk/zone-less/src/index.ts, libs/cdk/zone-less/src/rxjs/observable/interval.ts, libs/cdk/zone-less/src/rxjs/observable/timer.ts, libs/cdk/zone-less/src/rxjs/scheduler/Scheduler.ts, libs/cdk/zone-less/src/rxjs/scheduler/animation-frame/AnimationFrameScheduler.ts, libs/cdk/zone-less/src/rxjs/scheduler/animation-frame/animationFrame.ts, libs/cdk/zone-less/src/rxjs/scheduler/asap/AsapScheduler.ts, libs/cdk/zone-less/src/rxjs/scheduler/asap/asap.ts, libs/cdk/zone-less/src/rxjs/scheduler/async/AsyncScheduler.ts, libs/cdk/zone-less/src/rxjs/scheduler/async/async.ts, libs/cdk/zone-less/src/rxjs/scheduler/create-scheduler.ts, libs/cdk/zone-less/src/rxjs/scheduler/queue/QueueAction.ts, libs/cdk/zone-less/src/rxjs/scheduler/queue/QueueScheduler.ts, libs/cdk/zone-less/src/rxjs/scheduler/queue/queue.ts
I removed the implementation of all schedulers and just re-used the existing constructors.
I still left interfaces to make the compiler happy, since schedulers are not exposed publicly by rxjs (tho they don't affect the bundle size).
=> perf(cdk): use existing `rxjs` schedulers

.github/workflows/build-and-test.yml
This PR fixes e2e tests in the CI because:
- **demos-e2e** tests are broken
- **vanilla-case-studies-e2e** tests also broken
Suggestion for another PR: fixes demos-e2e (is it relevant?) and remove vanilla-case-studies-e2e
=> chore(ci): run only ssr e2e tests

libs/cdk/internals/scheduler/src/lib/scheduler.ts
This PR removes the error logs when bundling for a server target :
```
This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
```
The message is not relevant in a non-browser environment.
=> fix(cdk): skip logging error in ssr build

angular.json, libs/template/package.json, libs/template/schematics/migration.json, libs/template/schematics/src/common/utils/changes.ts, libs/template/schematics/src/common/utils/visitors.ts, libs/template/schematics/src/migrations/update-1-0-0/index.spec.ts, libs/template/schematics/src/migrations/update-1-0-0/index.ts, libs/template/tsconfig.schematics.json, libs/template/tsconfig.spec.json
As for now this migration script target versions `< 1.0.0` and assumes next version will be `1.0.0`, let me know if you want to release with another version.
=> Add migration schematic

libs/state/src/lib/index.ts, libs/state/src/lib/rxjs/interfaces/index.ts, libs/state/src/lib/rxjs/interfaces/pick-slice.ts, libs/state/src/lib/rxjs/operators/selectSlice.ts
the `selectSlice` operator returns the type `PickSlice` type which is not exported currently. This PR exports the `PickSlice` type for usage in other applications.
closes #821
=> refactor(cdk): export pick-slice type

libs/state/tsconfig.lib.json
Revert Ivy and let Ngcc do the job to avoid breaking ViewEngine apps. Fixes #928.
=> fix(state): disable Ivy + partial compilation

libs/state/docs/snippets/logic-comparison--increment-a-value.md
In this usage component is singular therefore the correct placement of the apostrophe is between the t and the s, i.e. `component's`
=> docs(state): fix typo and minor grammatical errors

libs/cdk/render-strategies/docs/README.md, libs/cdk/render-strategies/docs/basic-strategies.md, libs/cdk/render-strategies/docs/concurrent-strategies.md
Most important parts:
- `README.MD` - added snippet about `patchZone` and cross-links
- `basic-strategies.md` - `rxFor` uses `native` in the example
- `concurrent-strategies.md` - small text changes, updated frameBudget information (might be wrong, but that's from my experience), refactored code examples.
=> (Docs) render strategies examples

libs/template/let/src/lib/let.directive.ts, libs/template/let/src/lib/tests/let.directive.strategy.spec.ts
somehow the let directive is resetting the primary strategy of the global `StrategyProvider` on init.
I guess this is a leftover of times where each letdirective provided its very own `StrategyProvider`.
This PR removes the piece of code, because now each let directive has impact on a global scope which is not what we actually want
=> fix(template): don't override primary strategy 

libs/template/experimental/if/src/lib/if.directive.ts
Related to #1289, drop the `@angular/cdk` dependency. Let me know if you think the function `coerceBooleanProperty` should be exposed in the `@rx-angular/cdk/coercion` instead of being inlined in the `RxIf` directive. As it's only used here I prefer to not augment the API surface.
=> fix(template): drop @angular/cdk dep for rxIf

libs/cdk/internals/scheduler/src/lib/scheduler.spec.ts, libs/cdk/internals/scheduler/src/lib/scheduler.ts
requestPaint is exposed publicly by CDK as part of the internal scheduler. However, it is without any effect - it seems to be broken since 20c4197784fa83092a97e6c76060ab07e80e18fd. This PR fixes the functionality of requestPaint. Calling requestPaint will force the scheduler to 'yield to host'. 
Having two chunks of the UI one small one (~5ms, e.g. a side-bar) and a large one (~100ms, e.g. the main-content). Usually both chunks would be scheduled into the some frame and blocking the main thread. As an improvement one could call requestPaint in the smaller chunk and forcing the browser to render this part earlier.
=> fix(cdk): requestPaint should force a paint

libs/cdk/package.json, libs/state/package.json, libs/template/package.json
Resolves https://github.com/rx-angular/rx-angular/issues/1261. Under the hood, ng-packagr adds multiple peer dependencies to the distribution package.json with an incorrect version range. This fix ensures versions are well defined to deal with npm 7.
=> fix: add missing peerDependencies

libs/template/README.md
Added a note that both push and rxLet recognize only immutable changes
Closes #358
=> docs(template): add note about immutability changes for push & rxLet

libs/state/docs/api/rx-state.md, libs/state/selections/docs/operators/select.md, libs/state/selections/spec/select.spec.ts, libs/state/selections/src/index.ts, libs/state/selections/src/lib/operators/select.ts, libs/state/selections/src/lib/utils/guards.ts, libs/state/spec/rx-state.service.spec.ts, libs/state/src/lib/rx-state.service.ts
This PR adds two overloads to RxState's `select` method (and operator), which I think would make state projections more concise.
What I use `select` for most frequently is transforming one or more state properties reactively into the shape I need for my template. In other words, to project state using the declarative `f(state) = UI` approach. I often need a custom projection function for this (=> `map` operator), and also want the automatic optimization of only emitting changes to state props it depends on (=> `select` operator if single key, or `selectSlice` operator if multiple keys). This means I often write code like this:
```ts
isLoaded$ = this.state.select(
select('loading'),
map(loading => !loading),
);
filteredItems$ = this.state.select(
selectSlice(['items', 'textFilter']), …
```
=> Add overloads to select for more concise state projections

libs/template/docs/api/let-directive.md
Should not have `rx` prefix for suspense, error, complete
=> Fix rxLet context API docs

.github/workflows/build-and-test.yml
Build `docs` project on PR runs to force compilation errors and broken links to break the build before being merged.
*Most changes are because of formatting.*
=> chore: build docs on PR run

apps/docs/docusaurus.config.js
When I click *Edit this page* on for example https://www.rx-angular.io/docs/state, I navigate to https://github.com/rx-angular/rx-angular/edit/main/docs/state/state.mdx
When I click *Edit this page* on for example https://www.rx-angular.io/docs/state (or locally at http://localhost:3000/docs/state), I navigate to https://github.com/rx-angular/rx-angular/edit/main/apps/docs/docs/state/state.mdx
=> docs: correct base URL for *Edit this page* links

apps/docs/docusaurus.config.js, apps/docs/package.json, yarn.lock
This PR will close #1433 
I setup search using [docusaurus-search-local](https://github.com/easyops-cn/docusaurus-search-local).
To test it locally you will need to
* `nx run docs:build`
* serve the build docs in the dist folder. Navigate to dist/apps/docs and serve the files e.g. with `npx http-server` (https://github.com/http-party/http-server)
é voilá:
In the documentation of the search-plugin there's also an option mentioned on how to have the search available in dev mode  (without serving the build files from a web server) but at least i could not make it work with the nx setup. 
Hint: if you are not serving the build docs from a web server and instead run the project in dev mode with `nx serve docs` you will get a warning when using the search bar:
=> docs(docs): setup docs search

libs/template/for/src/lib/for.directive.ts, libs/template/for/src/lib/tests/for.directive.observable.spec.ts
just noticed we have a bug in rxFor that leads to multiple subscriptions being made to the incoming source value. That's definitely not what we want. Added `shareReplay` as a fix and implemented a test case to ensure we don't introduce the same bug again.
=> fix(template): rxFor: only subscribe once to value input

libs/cdk/coalescing/README.md
Changing word from "frequeltly" to "frequently"
=> docs: Resolve copy mistake of word "frequeltly"

libs/cdk/internals/scheduler/src/lib/scheduler.spec.ts, libs/cdk/internals/scheduler/src/lib/scheduler.ts
closing #1385 
as described in the linked issue, the scheduler was missing tasks added to the queue by NgZone. This PR fixes that behavior and makes sure we are not missing out cd events.
=> fix(cdk): make sure tasks queued by NgZone are also executed

apps/docs/docs/state/state.mdx
I guess this badge is by accident still there (in all other packages this has been removed)
=> docs(state): remove coverage status badge

apps/docs/docs/cdk/render-strategies/strategies/concurrent-strategies.md
as-is
`60frames/1000ms=16.6666ms`
should be
`1000ms/60frames=16.6666ms`
=> Fix incorrect frame budget equation

libs/template/for/src/lib/for.directive.ts
Type hint for object keys and inferred values is now shown.
=> fix(template): typing of track by key as keyof T

apps/demos/src/app/rx-angular-pocs/template/directives/switch/rx-switch-case.directive.ts, apps/docs/docs/template/api/rx-if-directive.md, libs/cdk/render-strategies/src/lib/model.ts, libs/cdk/render-strategies/src/lib/strategy-handling.ts, libs/cdk/template/src/lib/list-template-manager.ts, libs/template/for/src/lib/for.directive.ts, libs/template/if/src/lib/if.directive.ts, libs/template/let/src/lib/let.directive.ts, libs/template/push/src/lib/push.pipe.ts
Use `RxStrategyNames` for proper strategy input typing to achieve hinting of default strategies in template.
=> feat(template): use default strategy names type for template hint

apps/docs/docs/cdk/render-strategies/strategies/basic-strategies.md, apps/docs/docs/template/api/let-directive.md, apps/docs/docs/template/api/rx-for-directive.md, apps/docs/docs/template/api/rx-if-directive.md, libs/template/README.md
I added an example to the basic setup with standalone components and also fixed several typos or consistency stuff in the `@rx-angular/template` doc.
=> docs(template):  add setup example with standalone cmp and fix typos

libs/template/for/src/lib/for.directive.ts, libs/template/if/src/lib/if.directive.ts, libs/template/let/src/lib/let.directive.ts, libs/template/let/src/lib/tests/let.directive.parent-notification.spec.ts, libs/template/push/src/lib/push.pipe.ts
Resolves "@rx-angular/template": "^16.0.0" ->  Cannot read properties of undefined (reading 'config'). Fixes #1580.
=> fix(template): fix properties not initialized

libs/template/experimental/virtual-scrolling/src/lib/virtual-scroll-viewport.component.ts
use inject for dependency injection to prevent class instance members undefined errors
When virtual scroll feature used in a project with "target": "es2022" it's broken because class filed uses dependency injection field before initialization
`readonly viewRange = this.scrollStrategy.renderedRange$;`
throws an error and nothing is rendered.
Using inject instead of constructor injection fixes the issue
=> fix(template): virtual-scroll scrollStrategy dependency error in es2022

README.md
Adding a link to the push based company to the readme file
=> chore: add push-based.io link to readme

apps/docs/docs/isr/cache-variants.md, libs/isr/models/src/cache-handler.ts, libs/isr/models/src/index.ts, libs/isr/models/src/isr-handler-config.ts, libs/isr/server/src/isr-handler.ts
Implementation for Issue #1604 
This implementation has no breaking changes. It allows to specify different variants of the cache, e.g. for users who have a cookie to verify their logged in status. If no additional variants are specified, the functionality is unchanged. Also no modification to existing CacheHandler implementations is necessary.
Any number of variants can be specified via the ISRHandler configuration.
Each variant has an identifier and a callback function that recognizes the variant for a given request.
To enable on-demand cache invalidation, a simulateVariant function can also be specified, which can modify the request so that it can be identified for the variant.
=> feat(isr): add the possibility to create the cache in several variants

libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/dynamic-size-virtual-scroll-strategy.ts, libs/template/experimental/virtual-scrolling/src/lib/util.ts
Just noticed a really bad bug slipped into the virtual scroll package. On destruction the virtual scroll strategies raise an error as there is a bug in the unsubscription logic of the scroll listener. This will also lead to memory leaks as the scroll listener is never detached.
=> fix(template): fix memory leaks & runtime errors caused by virtual scroll

libs/state/src/lib/rx-state.service.ts
Simplification and elimination of handling the `connect`-overloads.
for reference: https://github.com/rx-angular/rx-angular/pull/1644#discussion_r1408870876
=> refactor(state): simplify connect implementation

libs/state/actions/src/lib/proxy.ts, libs/state/actions/src/lib/rx-actions.spec.ts
This repairs an issue where the on shorthand for side effects only supports single case lower case action. 
repo step https://stackblitz.com/edit/stackblitz-starters-ltqcqj?file=src%2Fmain.ts,src%2Fdata%2Fstate.ts
=> fix(state): on shorthand shouldn't toLowerCase

libs/state/actions/src/lib/types.ts
I'm not sure if this is wanted, however I kept having to type my side effects from the operator. Modified the type locally from NPM package and it solved my issue.  So I thought I'll see if this works for you and not just a local patch file
- Replace 'any' with inferred type from OperatorFunction's return type
- Enhance type safety and consistency across ActionEffects utility
=> refactor(state): ensure strong typing for sideEffectFn in ActionEffects

libs/template/push/src/lib/push.pipe.ts, libs/template/push/src/lib/tests/push.pipe.spec.ts
as elaborated in #1606 , using the `inject` method in pipes is causing them to use the ChildComponents CdRef. This is a problem for `RxPush`, as `detectChanges` won't update input bindings.
=> fix(template): use correct CdRef instance in RxPush

libs/cdk/zone-configurations/src/lib/zone-config.ts
=> fix(cdk): use `globalThis` instead of `ɵglobal` in zone-config

apps/docs/docs/state/actions/actions.mdx
[The docs are incorrect](https://www.rx-angular.io/docs/state/actions#use-custom-transform-functions)! My code looked like this:
```
<input name="name" (input)="ui.greet()" />
<div>{{ ui.greet$ | async }}</div>
```
However, I got an `Expected 1 arguments, but got 0.` error, yet I followed the docs perfectly! 
Turns out, I was missing `$event.target.value`. So here's how it should've looked like in the docs (or something similar to this):
```
<input name="name" (input)="ui.greet($event.target.value)" />
<div>{{ ui.greet$ | async }}</div>
```
And now it works. Hopefully, other devs won't be left discouraged to try this amazing tool because of this silly doc discrepancy!
=> Change `ui.greet()` to `ui.greet($event.target.value)` in actions.mdx

libs/template/experimental/virtual-scrolling/src/lib/virtual-for.directive.ts, libs/template/for/src/lib/for.directive.ts, libs/template/if/src/lib/if.directive.ts, libs/template/let/src/lib/let.directive.ts
Multiple users reported the issue that their IDE cannot infer the typings from our structural directives due to the `inject` method. Using the constructor based injection solves that issue. fixes #1616
=> fix(template): use constructor injection for templateRef

apps/docs/docs/template/api/unpatch-directive.md
out of the additional context of #1663
=> docs: add warning when using Unpatch on elements that refer a FormControl

apps/demos/src/app/features/template/rx-virtual-for/virtual-rendering/virtual-for-demo.component.ts, apps/demos/src/app/shared/debug-helper/value-provider/array-provider.service.ts, apps/demos/src/app/shared/debug-helper/value-provider/array-provider/array-provider.component.ts, apps/docs/docs/template/api/virtual-scrolling.mdx, libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/autosize-virtual-scroll-strategy.ts, libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/dynamic-size-virtual-scroll-strategy.ts, libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/fixed-size-virtual-scroll-strategy.ts, libs/template/experimental/virtual-scrolling/src/lib/util.ts, libs/template/experimental/virtual-scrolling/src/lib/virtual-for.directive.ts, libs/template/experimental/virtual-scrolling/src/lib/virtual-list-template-manager.ts, libs/template/experimental/virtual-scrolling/src/lib/virtual-scroll-viewport.component.ts, libs/template/experimental/virtual-scrolling/tests/autosize.cy.ts, libs/template/experimental/virtual-scrolling/tests/dynamic-size.cy.ts, libs/template/experimental/virtual-scrolling/tests/fixed-size.cy.ts
Sorry for delivering multiple things within a single PR...
This PR introduces the following new features:
* appendOnly mode
* initialScrollIndex input
as well as a bugfix for the virtual list template manager that sometimes produced bad diffs and a fix for a viewglitch caused by a mispositioned sentinel.
There is a new input `appendOnly: boolean` on the scroll strategies. Enabling this mode causes the rendered range to only increase - in any direction. See https://material.angular.io/cdk/scrolling/overview#append-only-mode
I hope this addresses https://github.com/rx-angular/rx-angular/issues/1686
There is a new input `initialScrollIndex: number` on the `RxVirtualScrollViewportComponent` which lets users define an initial index to scroll to. fixes …
=> feat(template): introduce appendOnly mode, initialScrollIndex & bugfixes

libs/eslint-plugin/package.json
Update @typescript-eslint/parser & utils dependencies for the eslint-plugin package to be in line with nx 18
Fixes #1707
=> feat(eslint): update dependencies to be compatible to nx 18

apps/docs/docs/state/actions/actions.mdx, apps/docs/docs/state/getting-started.mdx, libs/state/selections/spec/accumulation-observable.spec.ts, libs/state/selections/src/index.ts, libs/state/selections/src/lib/accumulation-observable.ts, libs/state/selections/src/lib/side-effect-observable.ts, libs/state/spec/rx-state.spec.ts, libs/state/src/index.ts, libs/state/src/lib/provide-rx-state-config.ts, libs/state/src/lib/rx-state.service.ts
Add provider functions to configure state through injection tokens:
- `provideRxStateConfig`
- `withAccumulator`
- `withSyncScheduler`
- `withScheduler`
Usage example:
```ts
bootstrapApplication(AppComponent, {
providers: [
provideRxStateConfig(
withAccumulator(myCustomAccumulator),
withSyncScheduler(),
),
],
});
```
It also exposes underlying injection tokens: 
- `RX_ACCUMULATOR_FN`
- `RX_STATE_SCHEDULER`
And finally, deprecate `RxState.setAccumulator` function.
closes #1621
=> feat(state): provide state config through injection tokens

libs/cdk/internals/scheduler/src/lib/scheduler.spec.ts, libs/cdk/internals/scheduler/src/lib/scheduler.ts, libs/cdk/internals/scheduler/src/lib/schedulerFeatureFlags.ts
Clean-up unused scheduler APIs, only `forceFramerate`, `scheduleCallback`, and `cancelCallback` are effectively used.
=> refactor(cdk): drop unused scheduler APIs

libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/autosize-virtual-scroll-strategy.ts, libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/dynamic-size-virtual-scroll-strategy.ts
as figured out by @KevinBelien in #1727 , the dynamic & autosize scroll strategies would not display anything on data sets smaller than the container height.
This PR fixes the calculation of the stable state.
Closing #1727
=> fix(template): virtual-for: properly calculate stable state

apps/docs/docs/template/api/rx-for-directive.mdx, libs/cdk/render-strategies/src/lib/config.ts
BREAKING CHANGE: It is possible that this change breaks the integration with 3rd party libraries, that are not up to date. If you are using the @rx-angular/template directives to project content into other components which don't use the new signal queries, they might not work properly anymore.
In order to fix this, you might want to set the parent flag to true on a global scope by providing an `RX_RENDER_STRATEGIES_CONFIG`. Another option is to set `parent: true` on a per directive basis.
Read more about this here: https://www.rx-angular.io/docs/template/performance-issues/handling-view-and-content-queries & here: https://push-based.io/article/new-features-for-rxangular-native-signal-support-and-improved-state#the-parent-flag-gets-deprecated
=> feat(template): set the parent flag to false by default

libs/isr/server/src/cache-regeneration.ts, libs/isr/server/src/isr-handler.ts, libs/isr/server/src/utils/cache-utils.ts
Refactor regeneration function for FileSystemCacheHandler so it supports variants and skipCachingOnHttpError config parameter. This fixes #1740 .
=> fix(isr): refactor cache regeneration function

apps/demos/src/app/features/template/rx-virtual-for/rx-virtual-for.menu.ts, apps/demos/src/app/features/template/rx-virtual-for/virtual-rendering/virtual-for-experiments.module.ts, apps/demos/src/app/features/template/rx-virtual-for/virtual-rendering/virtual-for-monkey-test.component.ts, libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/autosize-virtual-scroll-strategy.ts, libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/dynamic-size-virtual-scroll-strategy.ts, libs/template/experimental/virtual-scrolling/src/lib/virtual-for.directive.ts
This fix makes sure that the autosize & dynamic size strategies calculate correct values for the new anchorItem & renderedRange. Fixes #1744
=> fix(template): properly calculate range & anchor when values reset

apps/ssr-isr/project.json, apps/ssr-isr/server.ts, apps/ssr-isr/src/app/app.routes.ts, apps/ssr-isr/src/app/redirect.component.ts, libs/isr/server/src/isr-handler.ts
The main reason for this change is described in the issue https://github.com/rx-angular/rx-angular/issues/1738.  With this change, render exits if the `renderUrl` already handles the server response.
=> fix(isr): handle response sent in render

libs/isr/server/src/cache-regeneration.ts
This pull request fixes a bug in the CacheRegeneration class where the filtering of urlsOnHold was done based on the wrong variable. Instead of filtering by cacheKey, it was filtering by url. This caused incorrect removal of urls from urlsOnHold. The fix updates the filtering logic to use cacheKey instead, ensuring that the correct urls are removed from urlsOnHold.
=> fix(isr): filter urlsOnHold by cacheKey instead of url

apps/demos/src/app/features/template/rx-virtual-for/rx-virtual-for.menu.ts, apps/demos/src/app/features/template/rx-virtual-for/virtual-rendering/virtual-for-crazy-update.component.ts, apps/demos/src/app/features/template/rx-virtual-for/virtual-rendering/virtual-for-experiments.module.ts, libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/autosize-virtual-scroll-strategy.ts
thx to @FelixMuehling who noticed a nasty race condition in the resize observer implementation. Looks like the re-adjusting of the viewport based on the resizeObserver was sometimes using improper size values - causing views to get positioned out of order.
fixes #1746
=> fix(template): properly calc sizes when resizeobserver adjust viewport

libs/cdk/README.md, libs/state/README.md, libs/template/README.md
Update version compatibility table and link to official angular docs for cdk, state and template.
=> docs: update version compatibility table

apps/demos/src/app/features/template/rx-virtual-for/rx-virtual-for.menu.ts, apps/demos/src/app/features/template/rx-virtual-for/virtual-rendering/virtual-for-experiments.module.ts, apps/demos/src/app/features/template/rx-virtual-for/virtual-rendering/virtual-for-scrollto-demo.component.ts, libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/autosize-virtual-scroll-strategy.ts, libs/template/experimental/virtual-scrolling/src/lib/virtual-scroll-viewport.component.scss
In cases where we set an `initialScrollIndex` that leaves out some views in the beginning as initial paint - e.g. the range is something like 3:28. Subsequent scroll up events lead to a weird scroll behavior. 
rxFor creates the new views (+ attaching them as children to the DOM). The layout is now unstable - new nodes were added. Next, the scroll strategy asks for the dimensions of the newly created nodes which triggers a forced reflow - the layout will be stabilized. Before the scroll strategy does set position: absolute, chrome already rendered the node as position: relative, increasing the size of the scroll viewport and pushing down other nodes.
That's how the scroll position gets weirdly out of sync.
Fixes https://github.com/rx-angular/rx-angular/issues/1783
Setting an …
=> fix(template): fix initialScrollIndex in AutoSizeVirtualScrollStrategy

libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/autosize-virtual-scroll-strategy.ts
This PR fixes an issue where the autosize strategy wrongly calculates the anchorItem when items get deleted
=> fix(template): properly calculate anchorItem when removing items

libs/cdk/internals/core/src/index.ts, libs/cdk/internals/core/src/lib/toObservableMicrotask.ts, libs/state/src/lib/rx-state.service.ts, libs/template/for/src/lib/for.directive.ts, libs/template/if/src/lib/if.directive.ts, libs/template/let/src/lib/let.directive.ts
Instead of relying on a private API, I copied the impl and replace the private API with public & supported alternative.
=> fix: replace toObservableMicrotask private API with proper solution

libs/cdk/tsconfig.lib.json, libs/state/tsconfig.lib.json, libs/template/tsconfig.lib.json
somehow a misconfiguration sneaked in and our ts files weren't properly included in the tsconfig setup. this PR fixes all of those weird IDE issues @eneajaho and me were noticing recently:
* import paths not resolving
* `#` private marking not supported
* ...
=> fix: properly include files in tsconfig

libs/state/effects/src/lib/effects.service.spec.ts, libs/state/effects/src/lib/effects.service.ts
Use modern `DestroyRef` also within `RxEffects`
=> refactor(state): use DestroyRef within EffectsService

apps/demos/src/app/features/tutorials/basics/5-side-effects/side-effects.solution.component.ts, apps/demos/src/app/shared/debug-helper/value-provider/primitives-provider.service.ts, apps/demos/src/app/shared/viewport.service.ts, libs/state/spec/rx-state.component.spec.ts, libs/state/spec/rx-state.service.spec.ts, libs/state/spec/rx-state.spec.ts, libs/state/src/lib/rx-state.service.ts, libs/state/src/lib/rx-state.ts
Use modern `DestroyRef` instead of `OnDestroy` lifecycle hook
=> refactor(state): use DestroyRef instead of OnDestroy life cycle hook

libs/state/spec/rx-state.spec.ts
Seems like the issue was coming from Angular itself.
=> test(state): drop detecting changes twice

libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/autosize-virtual-scroll-strategy.ts
Fixes https://github.com/rx-angular/rx-angular/issues/1846
I only checked for virtual scrolling and not other parts of the template package. With that change my app built successfully.
=> fix(template): move import in virtual scrolling to rxjs/operators

libs/eslint-plugin/package.json
The published version of @rx-angular/eslint-plugin doesn't contain a license (See image). When using automated dependency scanning, you always get an error, that there is an invalid licence.
Adapted the package.json, so that the licence should be published.
=> fix(eslint): added license to package.json

package.json, yarn.lock
Updating the jscutlery/semver plugin.
@edbzn I've experienced a lot of issues recently when publishing our libs. Looks like it wouldn't run `build` after versioning. So it always tries to publish the last version again and fails. Is the update fixing it?
=> chore: update semver plugin

libs/state/effects/src/lib/effects.service.ts, libs/state/effects/src/lib/utils.ts
Drops `untilDestroyed` operator in favor of `takeUntilDestroyed`
=> refactor(state): drop untilDestroyed operator

libs/template/experimental/virtual-scrolling/src/lib/scroll-strategies/autosize-virtual-scroll-strategy.ts
Fixes #1812
I have looked into the issue I had with ionic components, where the height of the virtual scroll container was wrong. (#1812)
Ionic's `ion-item` component, which I used in my example, is having an height of 0px initially, which leads to `_virtualItems` being an array of `size: 0` and `cached: true` items (set in the `renderingStart$` observable).
Shortly after the initialization, the resize observer emits the actual height of the ionic item, and will add the difference in height to the `contentSize` (line 861). That will happen for each ionic item in my view. 
But before the second item difference will be calculated, the `positionByResizeObserver$` observable in `positionElements()` will call `updateElementSize()` for any further item. The `updateElementSize()` function will …
=> fix(template): using tombstoneSize for non-cached items with 0 height
