rx-angular/rx-angular

- libs/state/README.md
@rx-angular is awesome, thanks! 😻💖
> docs: `count` identifiers must be the same

- libs/template/src/lib/template.module.spec.ts
Add test suite for the template module, verifying the declarables that it exposes.
> test(template): add template module test suite

- libs/state/src/lib/core/operators/stateful.ts
- libs/template/src/lib/core/render-aware/strategies.ts
- libs/template/src/lib/core/utils/properties-weakmap.md
- libs/template/src/lib/core/utils/zone-checks.md
- libs/template/src/lib/core/utils/zone-checks.ts
Fixed some typo errors
p.s. thanks for your library!
> docs: fix typo

- libs/state/src/lib/rx-state.service.ts
- tools/scripts/docs/typescript-docs-renderer.ts
this extends #51 . improved wording of jsDocs and adapted docs renderer to output method signature aswell.
> update(docs) improved wording of jsDocs, improved docs renderer

- libs/state/README.md
- libs/state/README.md.old
- libs/state/docs/api.md
- libs/state/docs/api.md.old
- libs/state/docs/usage.md
- libs/state/src/lib/rx-state.service.ts
- tools/scripts/docs/typescript-docs-renderer.ts
improved and refactored docs.
- created docs folder
- moved API doc to own file
- moved USAGE doc to own file
- improved description and general appearance
> refactor(docs) improved & refactored docs

- libs/state/src/lib/rx-state.service.ts
- tools/scripts/docs/typescript-docs-parser.ts
- tools/scripts/docs/typescript-docs-renderer.ts
also adapted docs of rx-state file
> docs(update) updated docs-generator to fit styles

- libs/state/README.md
- libs/state/docs/snippets/global-state-vs-local-state.md
Basically a very-very tiny part of 'Layers of State' chapter + example of how to decide about state type.
> Global vs local state snippet

- libs/state/spec/core/accumulation-observable.spec.ts
- libs/state/spec/rx-state.service.spec.ts
- libs/state/src/lib/core/accumulation-observable.ts
- libs/state/src/lib/rx-state.service.ts
extend accumulator observable to take accumulation funions at runtime
> feat(state): extend accumulator observable to take accumulation functions at runtime

- libs/state/README.md
- libs/state/docs/snippets/composing-state-using-ngrx-selectors.md
Add a new example snippet using NgRx selectors with `@rx-angular/state`. Related to #100
> docs: Add ngrx selector example snippet

- libs/state/README.md
- libs/state/docs/snippets/manage-collections-with-ngrx-entity.md
Add new snippet utilizing `@ngrx/entity` for entity collection management with `@rx-angular/state`.
> docs(snippets): Add snippet explaining the use of ngrx-entity

- apps/template-demo/src/app/examples/coalescing/solution/coalescing.component.ts
- libs/template/src/lib/core/render-aware/render-aware_creator.ts
- libs/template/src/lib/render-strategies/strategies/local.strategy.ts
- fix for strategy behavior (when changed at runtime)
- improved initial rendering performance by skipping first cd run when not needed
> strategy behavior

- libs/template/spec/core/utils/zone-check.spec.ts
This pull request adds two tests to verify that `NgZone` and `NoopNgZone` have the behavior that is used to distinguish them from each other.
> test(template): test NgZone/NoopNgZone implementation

- libs/template/README.md
I just got a question about how & what to import.
> Add usage information

- libs/state/src/lib/rxjs/operators/selectSlice.ts
This PR serves to fix return types for `selectSlice` output Observables.
```ts
interface MyState {
items: string[];
title: string;
panelOpen: boolean;
}
const state$: Observable<MyState> = of({
title: 'myTitle',
items: ['foo', 'bar'],
panelOpen: true
});
const slice$ = state$.pipe(
selectSlice(['items', 'panelOpen'])
).subscribe(data => {
// data is unknown
});
const slice2$ = state$.pipe(
selectSlice({
title: (old, newTitle) => old !== newTitle
})
).subscribe(data => {
// data is unknown
});
```
```ts
const state$: Observable<MyState> = of({
title: 'myTitle',
items: ['foo', 'bar'],
panelOpen: true
});
const slice$ = state$.pipe(
selectSlice(['items', 'panelOpen'])
).subscribe(data => {
// data is { items: string[], panelOpen: boolean }
});
const slice2$ = state$.pipe(
selectSlice({ …
```
> Improve return types for selectSlice operator

- libs/state/docs/api/operators/distinct-until-some-changed.md
- libs/state/docs/api/operators/interfaces.md
- libs/state/docs/api/operators/select-slice.md
- libs/state/spec/rxjs/operators/distinctUntilSomeChanged.spec.ts
- libs/state/spec/rxjs/operators/selectSlice.spec.ts
- libs/state/src/lib/rxjs/interfaces/compare-fn.ts
- libs/state/src/lib/rxjs/interfaces/key-compare-map.ts
- libs/state/src/lib/rxjs/operators/distinctUntilSomeChanged.ts
- libs/state/src/lib/rxjs/operators/selectSlice.ts
> refactor selectSlice, distinctUntilSomeChanged, keyCompareMap

- apps/state-demo/src/app/examples/demo-basics/solution/demo-basics.component.ts
- libs/state/spec/core/utils/safe-pluck.spec.ts
DemoBasicsAdapterService was not provided anywhere
> Fix for state demo di

- libs/state/src/lib/rxjs/operators/selectSlice.ts
> fix(state): array length check strict

- .github/labeler.yml
- .github/workflows/build-and-test.yml
- README.md
> chore(github-actions) improved actions and labeler

- .github/labeler.yml
- libs/state/README.md
- libs/template/README.md
> docs(github-page):

- libs/state/jest.config.js
- libs/template/jest.config.js
> fix(coverage): exclude index files from coverage, adopted state config

- libs/state/README.md
Just added `Using RxState as Global State` link.
> Update state readme.md with link to global state snippet

- libs/template/spec/core/utils/zone-check.spec.ts
> fix(template): add tests for envZonePatched

- apps/tour-of-heroes/src/app/app.component.html
- apps/tour-of-heroes/src/app/dashboard/dashboard.component.html
- apps/tour-of-heroes/src/app/hero-detail/hero-detail.component.html
- apps/tour-of-heroes/src/app/hero-search/hero-search.component.html
- apps/tour-of-heroes/src/app/heroes/heroes.component.html
- apps/tour-of-heroes/src/app/messages/messages.component.html
- apps/tour-of-heroes/src/styles.scss
> adopt template-demo

- apps/template-demo/src/app/examples/prioritize-in-viewport/solution/let1.container.component.ts
- libs/template/src/lib/experimental/viewport-prio/viewport-prio.directive.ts
> fix(viewport-prio): fix demo in template

- libs/template/src/index.ts
> fix(export-experimental): export interfaces for custom strategies

- libs/template/spec/core/render-aware/render-aware_creator.spec.ts
implemented missing tests for render-aware_creator.ts
> test(render-aware): implemented missing tests

- libs/template/spec/render-strategies/rxjs/coalesceWith.spec.ts
implemented error handling tests for `coalesceWith` operator.
new test-coverage:
> test(coalesceWith): added tests for error handling

- libs/template/src/lib/push/push.module.ts
> fix(push-pipe): complete API docs

- libs/state/docs/api/rx-state.md
- libs/state/docs/usage.md
- libs/state/src/lib/rx-state.service.ts
> docs(setAccumulator): Create docs for API, usage and rx-state

- libs/template/spec/core/render-aware/render-aware_creator.spec.ts
- libs/template/spec/let/let.directive.strategy.spec.ts
- libs/template/spec/let/let.directive.template-binding.all.spec.ts
As for requirements for @rx-angular/template beta (https://github.com/BioPhoton/rx-angular/issues/202) we had to confirm proper test implementation for the `LetDirective`. This PR covers that requirement.
> Additional tests for LetDirective

- libs/state/docs/api/rx-state.md
- libs/state/docs/api/transformation-helpers/array/update.md
- libs/state/docs/usage.md
- libs/state/src/lib/rx-state.service.ts
- libs/template/spec/core/render-aware/render-aware_creator.spec.ts
- libs/template/spec/fixtures/emissions.ts
- libs/template/spec/fixtures/fixtures.ts
- libs/template/spec/fixtures/index.ts
- libs/template/spec/fixtures/mock-strategies.ts
- libs/template/spec/let/let.directive.strategy.spec.ts
- libs/template/spec/let/let.directive.template-binding.all.spec.ts
- libs/template/spec/render-strategies/render-strategies/detach.strategy.spec.ts
- libs/template/spec/render-strategies/render-strategies/global.strategy.spec.ts
- libs/template/spec/render-strategies/render-strategies/local.strategy.spec.ts
- libs/template/spec/render-strategies/render-strategies/native.strategy.spec.ts
- libs/template/spec/render-strategies/render-strategies/noop.strategy.spec.ts
- libs/template/spec/render-strategies/strategy.spec.ts
- libs/template/src/lib/core/model.ts
- libs/template/src/lib/core/render-aware/render-aware_creator.ts
- libs/template/src/lib/let/let.directive.ts
- libs/template/src/lib/push/push.module.ts
- libs/template/src/lib/push/push.pipe.ts
- libs/template/src/lib/render-strategies/strategies/local.strategy.ts
- libs/template/src/lib/render-strategies/strategies/native.strategy.ts
This PR implements a test set for all but scheduleCd :)
> test(strategies): implement tests

- docs/index.html
- docs/web/partials/_sidebar.md
This PR aims to fix some minor things on our docs page.
> Update docs description, fix favicon, fix slack url

- docs/web/partials/_coverpage.md
Local path is resolved incorrectly.
> docs(web): change coverpage logo url to global path

- libs/template/spec/core/utils/coalescing-manager.spec.ts
- libs/template/src/lib/core/utils/coalescing-manager.ts
implemented missing coalescing-manager tests in regards of #202
> test(coalescing-manager): implemented coalescing-manager tests

- libs/template/src/lib/core/utils/template-manager_creator.ts
> test(templateManager): fix tests

- libs/template/spec/fixtures/emissions.ts
- libs/template/spec/fixtures/fixtures.ts
- libs/template/spec/render-strategies/render-strategies/detach.strategy.spec.ts
- libs/template/spec/render-strategies/render-strategies/global.strategy.spec.ts
- libs/template/spec/render-strategies/render-strategies/local.strategy.spec.ts
- libs/template/spec/render-strategies/render-strategies/native.strategy.spec.ts
- libs/template/spec/render-strategies/render-strategies/noop.strategy.spec.ts
- libs/template/src/lib/render-strategies/strategies/local.strategy.ts
implemented missing tests and improved existing tests for strategies.
*done*:
* local
* noop
* detach
* native
*open*:
> test(render-strategies): improved render strategy tests

- libs/template/spec/render-strategies/static/static-coalesce.spec.ts
- libs/template/src/lib/render-strategies/static/static-coalesce.ts
> test(static-coalesce): added tests

- libs/template/spec/core/utils/get-global-this.spec.ts
- libs/template/spec/core/utils/get-zone-unpatched-api.spec.ts
- libs/template/spec/core/utils/view-engine-checks.spec.ts
- libs/template/spec/render-strategies/rxjs/scheduling/promiseTick.spec.ts
* added promiseTick catch test 
* fixed missing globalThis cleanups in other specs
> test(template): added missing promiseTick tests

- libs/template/spec/render-strategies/static/static-schedule-and-coalesced.spec.ts
- libs/template/src/lib/render-strategies/static/static-schedule-and-coalesced.ts
> test(static-coalesce-and-schedule): adopt signature, fix tests

- .github/labeler.yml
> chore(labaler): adopted labeling of PRs

- libs/template/spec/core/render-aware/render-aware_creator.spec.ts
With #312 and this, we are 100% :)
> Cover strategyName$ as observable in render-aware_creator

- .github/workflows/build-and-test.yml
- apps/tour-of-heroes-ngxs/src/app/app.component.html
- apps/tour-of-heroes-ngxs/src/app/app.module.ts
- apps/tour-of-heroes-ngxs/src/app/createPropertySelector.ts
- apps/tour-of-heroes-ngxs/src/app/dashboard/dashboard.component.ts
- apps/tour-of-heroes-ngxs/src/app/hero-detail/hero-detail.component.ts
- apps/tour-of-heroes-ngxs/src/app/hero-search/hero-search.component.ts
- apps/tour-of-heroes-ngxs/src/app/heroes/heroes.component.ts
- apps/tour-of-heroes-ngxs/src/app/ngxs/hero-feature/hero.facade.ts
- apps/tour-of-heroes-ngxs/src/app/ngxs/hero-feature/hero.selectors.ts
- apps/tour-of-heroes-ngxs/src/app/ngxs/hero-feature/hero.state.ts
- libs/state/docs/snippets/manage-global-state.md
- package.json
- yarn.lock
The objective of this PR is to provide a example of integrating RxAngular with NGXS using the best practices of both libraries.
> Provide an example of tour of heroes combining RxAngular with NGXS

- README.md
- docs/web/partials/_sidebar.md
> docs(web): replace slack link with discord

- docs/general/performance.md
> docs(general): add performance.md

- libs/template/spec/core/utils/template-manager_creator.spec.ts
- libs/template/src/lib/core/utils/template-manager_creator.ts
This change is needed to have multiple EmbeddedViews for the same template
> feat(template-manager): Add optional id to embeddedView name

- apps/demos/src/app/features/performance/sibling-component-structure/sibling-component-structure.component.ts
- apps/demos/src/app/shared/debug-helper/work/work.component.ts
- apps/demos/src/app/shared/debug-helper/work/work.module.ts
- apps/demos/src/app/shared/template-structures/sibling/sibling-progressive.component.ts
- apps/demos/src/app/shared/template-structures/sibling/sibling-push.component.ts
- apps/demos/src/app/shared/template-structures/sibling/sibling.module.ts
- apps/demos/src/app/shared/template-structures/sibling/sibling.scss
- apps/demos/src/app/shared/utils/measure.ts
- apps/demos/src/main.ts
- apps/demos/src/styles/_debug-helpers.scss
The interesting file is:
apps/demos/src/app/shared/utils/measure.ts
> docs(demos): add measure utils

- docs/index.html
- docs/web/partials/_sidebar.md
After the switch to a new routing relative urls not working on the real hosting, made a switch to the global path to raw files
> switch to raw files in docs/partials

- libs/state/src/lib/rx-state.service.ts
> fix stop stream when throw error in hold method

- apps/demos/src/app/features/concepts/global-order/push-v/push-v.module.ts
- apps/demos/src/app/features/concepts/global-order/push-v/v2-a.component.ts
- apps/demos/src/app/features/concepts/global-order/push-v/v2-b.component.ts
- apps/demos/src/app/features/concepts/global-order/shared/data.service.ts
- apps/demos/src/app/features/experiments/structural-directives/rx-for-poc/parent.component.ts
- apps/demos/src/app/features/experiments/structural-directives/rx-for-poc/rx-for-minimal.directive.ts
- apps/demos/src/app/features/experiments/structural-directives/rx-for-poc/rx-for-poc.module.ts
- apps/demos/src/app/features/experiments/structural-directives/utils.ts
- apps/demos/src/app/rx-angular-pocs/debug/dirty-check/dirty-checks.component.ts
- apps/demos/src/app/rx-angular-pocs/directives/for/rx-for.directive.ts
- apps/demos/src/app/rx-angular-pocs/render-strategies/default-strategies.ts
- apps/demos/src/polyfills.ts
- apps/demos/src/zone-flags.ts
> docs(case-studies): add nested case 3

- libs/state/package.json
> fix(schematics): remove undefined collection ref

- apps/demos/src/app/features/tutorials/basics/1-setup/Readme.md
- apps/demos/src/app/features/tutorials/basics/1-setup/setup.solution.component.ts
- apps/demos/src/app/features/tutorials/basics/1-setup/setup.start.component.ts
- apps/demos/src/app/features/tutorials/basics/2-input-bindings/Readme.md
- apps/demos/src/app/features/tutorials/basics/2-input-bindings/input-bindings.solution.component.ts
- apps/demos/src/app/features/tutorials/basics/2-input-bindings/input-bindings.start.component.ts
- apps/demos/src/app/features/tutorials/basics/3-output-bindings/output-bindings.solution.component.ts
- apps/demos/src/app/features/tutorials/basics/3-output-bindings/output-bindings.start.component.ts
- apps/demos/src/app/features/tutorials/basics/4-global-state/Readme.md
- apps/demos/src/app/features/tutorials/basics/4-global-state/global-state.solution.component.ts
- apps/demos/src/app/features/tutorials/basics/4-global-state/global-state.start.component.ts
- apps/demos/src/app/features/tutorials/basics/5-side-effects/Readme.md
- apps/demos/src/app/features/tutorials/basics/5-side-effects/side-effects.solution.component.ts
- apps/demos/src/app/features/tutorials/basics/5-side-effects/side-effects.start.component.ts
- apps/demos/src/app/features/tutorials/basics/6-presenter-pattern/adapter.ts
- apps/demos/src/app/features/tutorials/basics/6-presenter-pattern/presenter-pattern.solutuion.component.ts
- apps/demos/src/app/features/tutorials/basics/6-presenter-pattern/presenter-pattern.start.component.ts
- apps/demos/src/app/features/tutorials/basics/Readme.md
- apps/demos/src/app/features/tutorials/basics/tutorial-basics.module.ts
#WHY
the current basic tutorial isn't clear to read, the files are not comparable against each others. there are typos and missing context. 
#WHAT 
- add more description to the files. 
- show how the tutorial is structured. 
- make files comparable against each other
- add more link to any files discussed in the tutorial
> Clean up the basic tutorial

- libs/template/src/lib/experimental/unpatch/events/unpatch-events.experimental.directive.ts
> fix(template): allow empty `[unpatch]` input

- apps/demos/src/app/app-shell/app-shell-component/app-shell.component.scss
- apps/demos/src/app/features/template/rx-for/route-change/bg-color.pipe.ts
- apps/demos/src/app/features/template/rx-for/route-change/route-change.component.ts
- apps/demos/src/app/features/template/rx-for/route-change/route-change.module.ts
- apps/demos/src/app/features/template/rx-for/route-change/routed-ng-for.component.ts
- apps/demos/src/app/features/template/rx-for/route-change/routed-rx-for.component.ts
- apps/demos/src/app/features/template/rx-for/rx-for.menu.ts
- apps/demos/src/app/features/template/rx-for/rx-for.module.ts
> route-change concurrent mode demo

- libs/cdk/src/lib/template-management/template-manager.ts
fix for https://github.com/rx-angular/rx-angular/issues/584
> fix bug in first template init

- libs/cdk/src/lib/zone-configuration/zone-cfg.ts
Zone Flags:
- add assertion
- fix typing
> Add assertion to flags

- .github/workflows/build-and-test.yml
- yarn.lock
Following [this comment](https://github.com/rx-angular/rx-angular/pull/587#issuecomment-795698445) fix the undefined ref for master push Github action event.
PS need to be rebased after #587 because actually the lockfile is not in sync with master.
> chore(ci): remove --head + add --frozen-install arguments

- apps/demos/src/app/features/concepts/coalescing/coalescing.module.ts
- apps/demos/src/app/features/template/render-callback/render-callback.component.ts
- apps/demos/src/app/features/template/render-callback/render-callback.module.ts
- apps/demos/src/app/features/template/strategies/comparison/comparison.component.ts
- apps/demos/src/app/features/template/strategies/comparison/comparison.module.ts
- apps/demos/src/app/rx-angular-pocs/template/directives/switch/rx-switch-case.directive.ts
- apps/demos/src/app/rx-angular-pocs/template/directives/switch/rx-switch.directive.ts
- apps/demos/src/app/shared/debug-helper/strategy-select/strategy-select/strategy-select.component.ts
- libs/cdk/src/lib/cdk-config.ts
Fixed the most important demos:
* renderCallback
* rxContext (fixed rxSwitch aswell)
* strategy comparison
* coalescing
* push
* rxLet basics
> fix(demos): fix most of the demos

- libs/state/spec/transformation-helpers/array/update.spec.ts
- libs/state/src/lib/transformation-helpers/array/update.ts
Suggestion of changes for #426 . Happy to modify on suggestion.
> Do not insert updated item(s) if the source object is invalid or empty

- libs/template/src/lib/push/push.pipe.ts
> fix(template): import from another lib

- libs/state/src/lib/transformation-helpers/array/update.ts
just simplified the logic of update helper to check if it should proceed or return
> refactor(transformation-helper): simplify update helper

- README.md
Issue #303
I get this info from:
https://angular.io/guide/browser-support
> Add browser support

- libs/template/docs/performance-issues.md
Update the URL for The Deep Dive Episode 1: Mythbusting the AsyncPipe.
> docs: update podcast episode URL

- .github/workflows/build-and-test.yml
- libs/cdk/zone-configurations/ng-package.json
- libs/cdk/zone-configurations/package.json
- nx.json
- package.json
- yarn.lock
use nx-cloud for our ci setup. this includes:
* distributed task execution
* distributed caching
* nx-cloud agents
> chore: setup nx-cloud CI

- libs/template/docs/api/let-directive.md
> docs(let): fix template binding not found

- libs/template/schematics/migration.json
- libs/template/schematics/src/common/utils/changes.ts
- libs/template/schematics/src/migrations/update-1-0-0/index.spec.ts
- libs/template/schematics/src/migrations/update-1-0-0/index.ts
Update migration script to target the next prerelease version `1.0.0-beta.26` and fix various AST changes to migrate smoothly.
> fix(schematics): fix template migration

- libs/state/src/lib/core/utils/guards.ts
- libs/state/src/lib/transformation-helpers/_internals/valuesComparer.util.ts
- libs/state/src/lib/transformation-helpers/array/insert.ts
- libs/state/src/lib/transformation-helpers/array/update.ts
- libs/state/src/lib/transformation-helpers/array/upsert.ts
Average results from benchmark:
| Before  | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/7274335/139555718-a8a16bd1-0371-4579-822c-f7e3fa65a448.png) | ![image](https://user-images.githubusercontent.com/7274335/139555687-f27ae98b-7e25-4ddf-b001-f332e0ed5456.png)  |
| [Original code stackblitz](https://stackblitz.com/edit/angular-ivy-qkzlmf?file=src%2Fhelpers%2Fupdate.ts) | [Optimized code stackblitz](https://stackblitz.com/edit/angular-ivy-1bcmtv?file=src%2Fhelpers%2Fupdate.ts) |
----
closes #981
> refactor(state): optimize helpers performance

- apps/demos/src/app/app.module.ts
- libs/cdk/coercing/spec/coerceObservableWith.spec.ts
- libs/cdk/render-strategies/src/index.ts
- libs/cdk/render-strategies/src/lib/config.ts
- libs/cdk/render-strategies/src/lib/strategy-provider.service.ts
- libs/cdk/state/spec/accumulateObservables.spec.ts
- libs/cdk/template/spec/list-manager.spec.ts
- libs/cdk/template/spec/template-manager.spec.ts
- libs/state/spec/cdk/accumulation-observable.spec.ts
- libs/state/spec/cdk/side-effect-observable.spec.ts
Deprecate global config in favour of `RX_ANGULAR_RENDER_STRATEGIES_CONFIG`
> refactor(cdk): deprecate RX_ANGULAR_CONFIG 

- libs/cdk/README.md
- libs/state/README.md
- libs/template/README.md
added docs in the main section for each published library to indicate users should update using their respective cli tool.
> docs: add update docs for libs

- libs/cdk/CHANGELOG.md
Added description of the new library structure for cdk to changelog
> docs(cdk): add package migration description to changelog

- apps/demos/src/app/features/template/rx-let/rx-let.menu.ts
- apps/demos/src/app/features/template/rx-let/rx-let.routes.ts
- apps/demos/src/app/features/template/rx-let/scoping/intermediate.component.ts
- apps/demos/src/app/features/template/rx-let/scoping/rx-let-scoping.component.ts
- apps/demos/src/app/features/template/rx-let/scoping/rx-let-scoping.module.ts
- apps/demos/src/app/rx-angular-pocs/cdk/debug/dirty-check/dirty-checks.component.ts
- apps/demos/src/app/rx-angular-pocs/template/directives/for/rx-for.directive.ts
- apps/demos/src/app/rx-angular-pocs/template/directives/if-visible/if-visible.directive.ts
- apps/demos/src/app/rx-angular-pocs/template/directives/let/rx-let.directive.ts
- apps/demos/src/app/shared/debug-helper/strategy-select/strategy-select/strategy-select.component.ts
- libs/cdk/render-strategies/src/lib/config.ts
- libs/cdk/template/spec/list-manager.spec.ts
- libs/cdk/template/spec/template-manager.spec.ts
- libs/cdk/template/src/lib/list-template-manager.ts
- libs/cdk/template/src/lib/model.ts
- libs/cdk/template/src/lib/template-manager.ts
- libs/cdk/template/src/lib/utils.ts
- libs/template/experimental/for/src/lib/for.directive.ts
- libs/template/experimental/if/src/lib/if.directive.ts
- libs/template/let/src/lib/let.directive.ts
- libs/template/let/src/lib/tests/let.directive.parent-notification.spec.ts
- libs/template/let/src/lib/tests/let.directive.strategy.spec.ts
> perf(cdk): coalesce and optimize parent notification

- libs/cdk/notifications/src/lib/create-template-notifier.spec.ts
- libs/cdk/notifications/src/lib/create-template-notifier.ts
> Fix `null` error in template notifier

- libs/state/src/lib/rx-state.service.ts
Test case: do connect 200 000 times with multiple types of parameters.
> perf(state): improve connect checks performance

- libs/state/effects/src/lib/effects.service.ts
> fix(state): make rxjs imports to be compatible with rxjs v6

- libs/template/.eslintrc.json
- libs/template/experimental/for/src/lib/for.directive.ts
- libs/template/experimental/if/src/lib/if.directive.ts
- libs/template/let/src/lib/let.directive.ts
> chore: turn-off no-input-rename eslint rule

- libs/cdk/coercing/src/lib/coerceObservable.ts
- libs/cdk/template/src/lib/template-manager.ts
- libs/template/for/src/lib/for.directive.ts
- libs/template/let/src/lib/let.directive.ts
- libs/template/push/src/lib/push.pipe.ts
use rxjs version 6 compatible imports
closing #1403 
closing #1402
> fix: use rxjs version 6 compatible imports

- libs/cdk/project.json
- libs/state/project.json
- libs/template/project.json
> fix: turn off updating deps in dist package.json

- libs/state/selections/src/lib/operators/distinctUntilSomeChanged.ts
- libs/state/selections/src/lib/operators/stateful.ts
Minor docs adjustments to match arguments
> chore: adjust ts docs

- apps/docs/docs/template/api/rx-if-directive.md
- libs/template/if/src/lib/if.directive.ts
- libs/template/if/src/lib/tests/if.directive.context-templates.spec.ts
- libs/template/if/src/lib/tests/if.directive.context.spec.ts
Harmonize RxIf inputs as described in https://github.com/rx-angular/rx-angular/issues/431.
> refactor(template): harmonize RxIf triggers

- apps/docs/docs/template/api/let-directive.md
- libs/template/let/src/lib/let.directive.ts
- libs/template/let/src/lib/tests/let.directive.template-binding.all.spec.ts
Harmonize LetDirective inputs as described in https://github.com/rx-angular/rx-angular/issues/431.
> refactor(template): harmonize LetDirective triggers

- libs/cdk/package.json
- libs/state/package.json
- libs/template/package.json
- package.json
- yarn.lock
Fixes 8 vulnerabilities, when installing RxState #1493
> fix: bump ng-morph to fix vulnerabilities

- apps/docs/blog/2023-03-07-announcing-rxangular-cdk-and-template-1-0.md
We forgot to add the todo list from the announcement post 😅
> docs: remove list from announcement post

- apps/docs/docusaurus.config.js
- fix icon path
To test locally run `nx run docs:serve` and open `http://localhost:3000`
> chore: set favicon

- apps/docs/docs/state/actions/actions.mdx
##What has been done:
Updated Actions doc
Issue
#1561
> docs: update actions doc #1561

- libs/template/push/src/lib/push.pipe.ts
- libs/template/push/src/lib/tests/push.pipe.spec.ts
Same issue as this one: https://github.com/angular/angular/issues/50382
Same fix as this one: https://github.com/angular/angular/pull/50522
Repro: https://stackblitz.com/edit/stackblitz-starters-mec8lw
> fix(template): untrack subscription and unsubscription in push pipe

- libs/state/spec/rx-state.service.spec.ts
- libs/state/src/lib/rx-state.service.ts
Fixes make the state readonly #1617, and also fixes RxState should be readonly? #1449.
> feat(state): make state readonly

- apps/docs/docs/state/tutorials/passing-observables-directly.md
> docs: describe that Observable Inputs should not be overriden

- apps/docs/docs/template/concepts/local-variables.md
[This part of docs](https://www.rx-angular.io/docs/template/concepts/local-variables) was unclear to me (at first glance). 
My suggestion is to include `*ngIf="num$ as n"`.
It's minuscule, but probably worth it for the _clarity_ 🤌
Am I overthinking this?
> Update local-variables.md to include `*ngIf="num$ as n"`

- .eslintrc.json
- libs/state/src/lib/rx-state.service.ts
resolves https://github.com/rx-angular/rx-angular/issues/1634
I'm feel very sorry for a long time with this issue, but covid hits me hard last weeks : < 
**Test**
✔  nx run state:test (15s)
✔  nx run demos:test (924ms)
✔  nx run ssr:test (912ms)
NX   Successfully ran target test for 3 projects 
Can't wait for the next issue i can take :D
> Readable generic names #1634

- libs/state/selections/src/lib/operators/select.ts
- libs/state/selections/src/lib/utils/guards.ts
- libs/state/spec/rx-state.service.spec.ts
- libs/state/src/lib/rx-state.service.ts
Default transform function for selecting state
fixes #1683
> [State] feat - default transform function for select

- libs/isr/models/src/isr-handler-config.ts
- libs/isr/server/src/isr-handler.ts
- libs/isr/server/src/utils/render-url.ts
Implementation for Issue #1705
Closes #1705
> feat(isr): add `inlineCriticalCss` support

- apps/docs/docusaurus.config.js
resolves https://github.com/rx-angular/rx-angular/issues/1691
meta tags preview
> fix: meta tags for docusaurus

- libs/isr/server/src/utils/render-url.ts
Yesterday, I tried to run the ISR package in my project and found this issue.
I know there is an open PR, but if you don't get a response, here is a clean change.
Closes #1687
> fix(isr): invalidation issue with url

- libs/isr/browser/src/isr.service.ts
Hi,
This is just some simple refactor. It is useful to me. If you guys like it. I will push more from my fork
Thanks for the great library.
Cheers!
> chore(isr): refactor IsrService patchState method

- libs/isr/server/src/cache-handlers/filesystem-cache-handler.spec.ts
- libs/isr/server/src/cache-handlers/filesystem-cache-handler.ts
> feat(isr): handle query string for filesystem cache #1690

- libs/isr/server/src/cache-handlers/in-memory-cache-handler.ts
> fix(isr): in memory cache handler should use extends  #1736

- libs/isr/models/src/cache-handler.ts
- libs/isr/models/src/isr-service.interface.ts
- libs/isr/server/src/cache-handlers/filesystem-cache-handler.ts
- libs/isr/server/src/cache-handlers/in-memory-cache-handler.ts
- libs/isr/server/src/cache-regeneration.ts
- libs/isr/server/src/isr-handler.ts
- libs/isr/server/src/isr-logger.ts
- libs/isr/server/src/isr-server.service.ts
- libs/isr/server/src/isr.module.ts
- libs/isr/server/src/provide-isr.ts
- libs/isr/server/src/utils/add-isr-data-before-serialized.ts
- libs/isr/server/src/utils/get-isr-options.ts
- libs/isr/server/src/utils/render-url.ts
I ran this locally, everything seems working fine. This will be the end of refactoring for IRS. I plan to add more features to my fork, and I will make a PR if you want
> refactor(isr): eslint issues

- apps/docs/docs/isr/getting-started.md
- libs/isr/models/src/isr-handler-config.ts
- libs/isr/server/src/cache-regeneration.ts
- libs/isr/server/src/isr-handler.ts
- libs/isr/server/src/utils/cache-utils.spec.ts
- libs/isr/server/src/utils/cache-utils.ts
> feat(isr): add allowed query params options #1743

- apps/ssr-isr/server.ts
- libs/isr/models/src/isr-handler-config.ts
- libs/isr/server/src/cache-generation.ts
- libs/isr/server/src/cache-handlers/filesystem-cache-handler.ts
- libs/isr/server/src/isr-handler.ts
#1761 
note: this one will need to wait until #1760 is merged
> feat(isr): nonBlockingRender & backgroundRevalidation

- libs/state/spec/rx-state.spec.ts
- libs/state/src/lib/rx-state.ts
> feat(state): expose asReadOnly() when create state instance using functional approach

- libs/isr/README.md
> docs(isr): add version compatibility table

- .github/actions/setup/action.yml
- .github/workflows/build-and-test.yml
- .nx/workflows/dynamic-changesets.yml
- nx.json
not sure about the `parallel` usage, but everything else should be just fine. Spent some time on tweaking the agents setup. We of course could opt-in to use those xtra-large images ... but i'm kind of hesitating to use so much power for our little lib :D
> chore: reduce CI complexity. use nx cloud agents

- apps/docs/docs/isr/irs-configuration.md
> docs(isr): add isr handler configuration documentation

- libs/isr/models/src/index.ts
- libs/isr/models/src/isr-handler-config.ts
- libs/isr/server/src/cache-generation.ts
- libs/isr/server/src/isr-handler.ts
- libs/isr/server/src/utils/cache-utils.spec.ts
- libs/isr/server/src/utils/cache-utils.ts
> feat(isr): add custom cache key generation logic

- apps/docs/docs/template/virtual-view-directive.mdx
A small unimportant detail was missed in the docs :D
> docs(template): add import statements for virtual-view
